#include<stdio.h>
typedef long long ll;

//factorial function by iteration
ll fact_by_iteration(ll n){
	
	ll ans = 1, i;
	for(i = 2; i <= n; i++)
		ans *= i;
	return ans;
}


//factorial function by recursion
ll fact_by_recursion(ll n) {
	// base  condition :- when n == 1 return 1
	return (n == (ll)1 ? (ll)1 : n * fact_by_recursion(n - 1)); 
}

int main() {
	
	ll n;
	printf("enter the number :- ");
	scanf("%lld", &n);
	
	ll value1 = fact_by_recursion(n);
	ll value2 = fact_by_iteration(n);
	
	printf("the value generated by recursion :- %lld\n", value1);
	printf("the value generated by iteration :- %lld\n", value2);
	
	return 0;
}
